<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="<?=CONTENT_AUTHOR?>"/> 
    <meta name="description" content="<?=$this->description?>" />
    <link rel="shortcut icon" href="<?=SITE_URL?>assets/ico/favicon.ico">

    <title><?=$this->title." :: ".STANDARD_TITLE?></title>

   	<link href="<?=SITE_URL?>css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="<?=$this->slug?>">