
  	<div class="container">
        <h1 class="cover-heading">Threefold</h1>
        <p class="lead">It's alive!</p>
        Some examples:<br>
        <ul>
        	<li><a href="<?=SITE_URL?>my_beautiful_page">My_beautiful_page</a></li>
        	<li>Fruits:
        		<ul>
        			<li><a href="<?=SITE_URL?>fruits/apple">Apple</a></li>
        			<li><a href="<?=SITE_URL?>fruits/banana">Banana</a></li>
        		</ul>
        	</li>
        </ul>
  	</div>
  	