
  	<div class="container">
        <h2>It's alive!</h2>
        Some examples:<br>
        <ul>
        	<li><a href="<?=SITE_URL?>my_beautiful_page">My_beautiful_page</a></li>
        	<li>Fruits:
        		<ul>
        			<li><a href="<?=SITE_URL?>fruits/apple">Apple</a></li>
        			<li><a href="<?=SITE_URL?>fruits/banana">Banana</a></li>
        		</ul>
        	</li>
          <li><a href="<?=SITE_URL?>nonexistingpage">Non-existing page</li>
        </ul>
  	</div>
  	